server:
  port: 0

spring:
  config:
    activate:
      on-profile: prod

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true                        # SMTP 서버에 인증 필요한 경우 true로 지정한다. Gmail SMTP 서버는 인증을 요구하기 때문에 true로 설정해야 한다.
          starttls:                         # SMTP 서버에 TLS를 사용할 것인지 여부를 지정한다. Gmail SMTP 서버는 TLS를 사용해야 하기 때문에 true로 설정해야 한다.
            enable: true

      auth-code-expiration-millis: ${EMAIL_AUTH_CODE_EXPIRATION_MILLIS}


  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      ddl-auto: update
      format_sql: true
    show-sql: true

  # Replication 설정
  datasource:
    url: ${MASTER_DB_URL}
    username: ${MASTER_DB_USERNAME}
    password: ${MASTER_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 설정
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
    web:
      pageable:
        one-indexed-parameters: true
JWT:
  secret-key: ${JWT_SECRET_KEY}
  header: Authorization
  prefix: Bearer
  token:
    access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}


# 유레카 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

  # 랜덤포트로
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}